version: '3.8'
services:
  dev-db:
    container_name : djangogirls_dev
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: djangogirls
    networks:
      - localhost
 
networks:
  localhost: