# Generated by Django 4.1.7 on 2023-02-16 02:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_tag_post_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tag",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
