# Generated by Django 4.1.7 on 2023-02-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_remove_post_category_post_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="visits",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="posts", to="blog.category"
            ),
        ),
    ]
